import { CreateStateDto } from "../../../../app/dtos/states/create-state.dto"

export const data: CreateStateDto[] = [
  {
    name: "Bengo",
    foundedAt: "1980-04-26",
    capital: "Caxito",
    area: "31.371 km²",
    phonePrefix: "034",
    website: "https://www.bengo.gov.ao",
    counties: [
      "Ambriz",
      "Bula Atumba",
      "Dande",
      "Dembos",
      "Nambuangongo",
      "Pango Aluquém",
    ],
  },
  {
    name: "Benguela",
    foundedAt: "1617",
    capital: "Benguela",
    area: "39.827 km²",
    phonePrefix: "+244",
    website: "https://www.benguela.gov.ao",
    counties: [
      "Balombo",
      "Baía Farta",
      "Benguela",
      "Bocoio",
      "Caimbambo",
      "Catumbela",
      "Chongorói",
      "Cubal",
      "Ganda",
      "Lobito",
    ],
  },
  {
    name: "Bié",
    foundedAt: "1922-05-01",
    capital: "Cuíto",
    area: "70.314 km²",
    phonePrefix: "+244",
    website: "https://www.bie.gov.ao",
    counties: [
      "Andulo",
      "Camacupa",
      "Catabola",
      "Chinguar",
      "Chitembo",
      "Cuemba",
      "Cunhinga",
      "Cuíto",
      "Nharea",
    ],
  },
  {
    name: "Cabinda",
    foundedAt: "1919-02-28",
    capital: "Cabinda",
    area: "7.283 km²",
    phonePrefix: "+244",
    website: "https://www.cabinda.gov.ao",
    counties: ["Belize", "Buco-Zau", "Cabinda", "Cacongo"],
  },
  {
    name: "Cuando Cubango",
    foundedAt: "1961-10-21",
    capital: "Menongue",
    area: "199.049 km²",
    phonePrefix: "049",
    website: "https://www.cuandocubango.gov.ao",
    counties: [
      "Calai",
      "Cuangar",
      "Cuchi",
      "Cuito Cuanavale",
      "Dirico",
      "Mavinga",
      "Menongue",
      "Nancova",
      "Rivungo",
    ],
  },
  {
    name: "Cuanza Norte",
    foundedAt: "1914-08-15",
    capital: "Ndalatando",
    area: "24.110 km²",
    phonePrefix: "035",
    website: "https://www.cuanzanorte.gov.ao",
    counties: [
      "Ambaca",
      "Banga",
      "Bolongongo",
      "Cambambe",
      "Cazengo",
      "Golungo Alto",
      "Gonguembo",
      "Lucala",
      "Quiculungo",
      "Samba Caju",
    ],
  },
  {
    name: "Cuanza Sul",
    foundedAt: "1917-09-15",
    capital: "Sumbe",
    area: "55.660 km²",
    phonePrefix: "+244",
    website: "https://www.cuanzasul.gov.ao",
    counties: [
      "Amboim",
      "Cassongue",
      "Cela",
      "Conda",
      "Ebo",
      "Libolo",
      "Mussende",
      "Porto Amboim",
      "Quibala",
      "Quilenda",
      "Seles",
      "Sumbe",
    ],
  },
  {
    name: "Cunene",
    foundedAt: "1970-07-10",
    capital: "Ondjiva",
    area: "78.342 km²",
    phonePrefix: "035",
    website: "https://www.cunene.gov.ao",
    counties: [
      "Cahama",
      "Cuanhama",
      "Curoca",
      "Cuvelai",
      "Namacunde",
      "Ombadja",
    ],
  },
  {
    name: "Huambo",
    foundedAt: "1912-09-21",
    capital: "Huambo",
    area: "35.771 km²",
    phonePrefix: "+244",
    website: "https://www.huambo.gov.ao",
    counties: [
      "Bailundo",
      "Cachiungo",
      "Caála",
      "Ecunha",
      "Huambo",
      "Londuimbali",
      "Longonjo",
      "Mungo",
      "Chicala-Choloanga",
      "Chinjenje",
      "Ucuma",
    ],
  },
  {
    name: "Huíla",
    foundedAt: "1901-09-02",
    capital: "Lubango",
    area: "79.022 km²",
    phonePrefix: "+244",
    website: "https://www.huila.gov.ao",
    counties: [
      "Caconda",
      "Cacula",
      "Caluquembe",
      "Chiange",
      "Chibia",
      "Chicomba",
      "Chipindo",
      "Cuvango",
      "Humpata",
      "Jamba",
      "Lubango",
      "Matala",
      "Quilengues",
      "Quipungo",
    ],
  },
  {
    name: "Luanda",
    foundedAt: "1576-01-01",
    capital: "Luanda",
    area: "18.826 km²",
    phonePrefix: "222",
    website: "https://www.luanda.gov.ao",
    counties: [
      "Belas",
      "Cacuaco",
      "Cazenga",
      "Ícolo e Bengo",
      "Luanda",
      "Quilamba Quiaxi",
      "Quissama",
      "Talatona",
      "Viana",
    ],
  },
  {
    name: "Lunda Norte",
    foundedAt: "1978-07-04",
    capital: "Dundo",
    area: "103.760 km²",
    phonePrefix: "+244",
    website: "https://www.lundanorte.gov.ao",
    counties: [
      "Cambulo",
      "Capenda-Camulemba",
      "Caungula",
      "Chitato",
      "Cuango",
      "Cuílo",
      "Lóvua",
      "Lubalo",
      "Lucapa",
      "Xá-Muteba",
    ],
  },
  {
    name: "Lunda Sul",
    foundedAt: "1895-07-13",
    capital: "Saurimo",
    area: "77.636 km²",
    phonePrefix: "+244",
    website: "https://www.lundasul.gov.ao",
    counties: ["Cacolo", "Dala", "Muconda", "Saurimo"],
  },
  {
    name: "Malanje",
    foundedAt: "1921",
    capital: "Malanje",
    area: "98.302 km²",
    phonePrefix: "+244",
    website: "https://www.malanje.gov.ao",
    counties: [
      "Cacuso",
      "Calandula",
      "Cambundi-Catembo",
      "Cangandala",
      "Caombo",
      "Cuaba Nzoji",
      "Cunda-Dia-Baze",
      "Luquembo",
      "Malanje",
      "Marimba",
      "Massango",
      "Mucari",
      "Quela",
      "Quirima",
    ],
  },
  {
    name: "Moxico",
    foundedAt: "1917-09-15",
    capital: "Luena",
    area: "223.023 km²",
    phonePrefix: "+244",
    website: "https://www.moxico.gov.ao",
    counties: [
      "Alto Zambeze",
      "Bundas",
      "Camanongue",
      "Léua",
      "Luau",
      "Luacano",
      "Luchazes",
      "Cameia",
      "Moxico",
    ],
  },
  {
    name: "Namibe",
    foundedAt: "1849-04-19",
    capital: "Moçâmedes",
    area: "57.091 km²",
    phonePrefix: "+244",
    website: "https://www.namibe.gov.ao",
    counties: ["Bibala", "Camucuio", "Moçâmedes", "Tômbua", "Virei"],
  },
  {
    name: "Uíge",
    foundedAt: "1887-05-31",
    capital: "Uíge",
    area: "58.698 km²",
    phonePrefix: "+244",
    website: "https://www.uige.gov.ao",
    counties: [
      "Alto Cauale",
      "Ambuíla",
      "Bembe",
      "Buengas",
      "Bungo",
      "Damba",
      "Milunga",
      "Mucaba",
      "Negage",
      "Puri",
      "Quimbele",
      "Quitexe",
      "Sanza Pombo",
      "Songo",
      "Uíge",
      "Zombo",
    ],
  },
  {
    name: "Zaire",
    foundedAt: "1961-04-01",
    capital: "Mbanza Congo",
    area: "40.138 km²",
    phonePrefix: "+232",
    website: "https://www.zaire.gov.ao",
    counties: ["Cuimba", "Mabanza Congo", "Nóqui", "Nezeto", "Soio", "Tomboco"],
  },
]
